<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
     name="echo"
     targetNamespace="http://xmlns.oracle.com/sandbox_jws/echo/echo"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/sandbox_jws/echo/echo"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:documentation>
        <abstractWSDL>echo.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="echo">
        <plnk:role name="echoProvider">
            <plnk:portType name="client:echo"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/sandbox_jws/echo/echo" schemaLocation="echo.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="echoRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:message name="echoResponseMessage">
        <wsdl:part name="payload" element="client:processResponse"/>
    </wsdl:message>
    <wsdl:portType name="echo">
        <wsdl:operation name="process">
            <wsdl:input message="client:echoRequestMessage"/>
            <wsdl:output message="client:echoResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="echoBinding" type="client:echo">
        <soap:binding xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal" namespace="http://xmlns.oracle.com/sandbox_jws/echo/echo"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal" namespace="http://xmlns.oracle.com/sandbox_jws/echo/echo"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="echo_client_ep">
        <wsdl:port name="echo_pt" binding="client:echoBinding">
            <soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="http://orabpm-server:8001/soa-infra/services/default/echo/echo_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
